import moment from 'moment';

const users = [
  { id: 1, name: 'Lord Gaben', avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg' },
  { id: 2, name: 'Pickle Rick', avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png' },
  { id: 3, name: 'Baby Yoda', avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg' },
];

// Helper to create timestamps from days ago
const daysAgo = (days, hours = 0, minutes = 0) =>
  moment()
    .subtract(days, 'days')
    .subtract(hours, 'hours')
    .subtract(minutes, 'minutes')
    .toISOString();

export const activitiesData = {
  activities: [
    {
      id: 1,
      type: 'comment_added',
      issueId: 103,
      issueTitle: 'Implement dark mode',
      userId: 2,
      user: users[1],
      data: {
        commentBody: 'Great progress so far! The theme switcher looks good.',
      },
      isRead: false,
      createdAt: daysAgo(0, 2, 30),
    },
    {
      id: 2,
      type: 'status_changed',
      issueId: 101,
      issueTitle: 'Add new navigation component',
      userId: 1,
      user: users[0],
      data: {
        fromStatus: 'backlog',
        toStatus: 'inprogress',
      },
      isRead: false,
      createdAt: daysAgo(0, 5, 15),
    },
    {
      id: 3,
      type: 'assignee_added',
      issueId: 102,
      issueTitle: 'Fix login form validation',
      userId: 1,
      user: users[0],
      data: {
        assigneeName: 'Pickle Rick',
      },
      isRead: false,
      createdAt: daysAgo(0, 8, 45),
    },
    {
      id: 4,
      type: 'priority_changed',
      issueId: 102,
      issueTitle: 'Fix login form validation',
      userId: 2,
      user: users[1],
      data: {
        fromPriority: '3',
        toPriority: '2',
      },
      isRead: true,
      createdAt: daysAgo(1, 2, 0),
    },
    {
      id: 5,
      type: 'estimate_changed',
      issueId: 103,
      issueTitle: 'Implement dark mode',
      userId: 3,
      user: users[2],
      data: {
        oldEstimate: 12,
        newEstimate: 16,
      },
      isRead: false,
      createdAt: daysAgo(1, 6, 20),
    },
    {
      id: 6,
      type: 'status_changed',
      issueId: 104,
      issueTitle: 'Update API documentation',
      userId: 3,
      user: users[2],
      data: {
        fromStatus: 'inprogress',
        toStatus: 'done',
      },
      isRead: true,
      createdAt: daysAgo(1, 14, 30),
    },
    {
      id: 7,
      type: 'assignee_removed',
      issueId: 101,
      issueTitle: 'Add new navigation component',
      userId: 1,
      user: users[0],
      data: {
        assigneeName: 'Baby Yoda',
      },
      isRead: true,
      createdAt: daysAgo(2, 3, 10),
    },
    {
      id: 8,
      type: 'comment_added',
      issueId: 101,
      issueTitle: 'Add new navigation component',
      userId: 2,
      user: users[1],
      data: {
        commentBody: 'Should we consider adding breadcrumb navigation as well? It would help users understand their...',
      },
      isRead: false,
      createdAt: daysAgo(2, 10, 0),
    },
    {
      id: 9,
      type: 'status_changed',
      issueId: 103,
      issueTitle: 'Implement dark mode',
      userId: 1,
      user: users[0],
      data: {
        fromStatus: 'selected',
        toStatus: 'inprogress',
      },
      isRead: true,
      createdAt: daysAgo(3, 1, 45),
    },
    {
      id: 10,
      type: 'issue_created',
      issueId: 105,
      issueTitle: 'Add keyboard shortcuts',
      userId: 1,
      user: users[0],
      data: {},
      isRead: true,
      createdAt: daysAgo(3, 7, 30),
    },
    {
      id: 11,
      type: 'assignee_added',
      issueId: 103,
      issueTitle: 'Implement dark mode',
      userId: 1,
      user: users[0],
      data: {
        assigneeName: 'Baby Yoda',
      },
      isRead: true,
      createdAt: daysAgo(3, 9, 15),
    },
    {
      id: 12,
      type: 'priority_changed',
      issueId: 105,
      issueTitle: 'Add keyboard shortcuts',
      userId: 3,
      user: users[2],
      data: {
        fromPriority: '4',
        toPriority: '3',
      },
      isRead: true,
      createdAt: daysAgo(3, 12, 0),
    },
    {
      id: 13,
      type: 'comment_added',
      issueId: 104,
      issueTitle: 'Update API documentation',
      userId: 1,
      user: users[0],
      data: {
        commentBody:
          'Please make sure to include examples for all the new endpoints. The examples really help new developers.',
      },
      isRead: true,
      createdAt: daysAgo(4, 4, 20),
    },
    {
      id: 14,
      type: 'estimate_changed',
      issueId: 101,
      issueTitle: 'Add new navigation component',
      userId: 2,
      user: users[1],
      data: {
        oldEstimate: 6,
        newEstimate: 8,
      },
      isRead: true,
      createdAt: daysAgo(4, 8, 40),
    },
    {
      id: 15,
      type: 'status_changed',
      issueId: 102,
      issueTitle: 'Fix login form validation',
      userId: 2,
      user: users[1],
      data: {
        fromStatus: 'backlog',
        toStatus: 'selected',
      },
      isRead: true,
      createdAt: daysAgo(4, 11, 10),
    },
    {
      id: 16,
      type: 'assignee_added',
      issueId: 101,
      issueTitle: 'Add new navigation component',
      userId: 1,
      user: users[0],
      data: {
        assigneeName: 'Lord Gaben',
      },
      isRead: true,
      createdAt: daysAgo(5, 2, 30),
    },
    {
      id: 17,
      type: 'assignee_added',
      issueId: 101,
      issueTitle: 'Add new navigation component',
      userId: 1,
      user: users[0],
      data: {
        assigneeName: 'Pickle Rick',
      },
      isRead: true,
      createdAt: daysAgo(5, 2, 35),
    },
    {
      id: 18,
      type: 'issue_created',
      issueId: 104,
      issueTitle: 'Update API documentation',
      userId: 3,
      user: users[2],
      data: {},
      isRead: true,
      createdAt: daysAgo(5, 6, 0),
    },
    {
      id: 19,
      type: 'comment_added',
      issueId: 102,
      issueTitle: 'Fix login form validation',
      userId: 3,
      user: users[2],
      data: {
        commentBody: 'I found the issue - the regex pattern was incorrect. Will push a fix shortly.',
      },
      isRead: true,
      createdAt: daysAgo(5, 13, 25),
    },
    {
      id: 20,
      type: 'status_changed',
      issueId: 104,
      issueTitle: 'Update API documentation',
      userId: 3,
      user: users[2],
      data: {
        fromStatus: 'selected',
        toStatus: 'inprogress',
      },
      isRead: true,
      createdAt: daysAgo(6, 1, 0),
    },
    {
      id: 21,
      type: 'priority_changed',
      issueId: 101,
      issueTitle: 'Add new navigation component',
      userId: 1,
      user: users[0],
      data: {
        fromPriority: '2',
        toPriority: '3',
      },
      isRead: true,
      createdAt: daysAgo(6, 4, 50),
    },
    {
      id: 22,
      type: 'issue_created',
      issueId: 103,
      issueTitle: 'Implement dark mode',
      userId: 1,
      user: users[0],
      data: {},
      isRead: false,
      createdAt: daysAgo(6, 9, 0),
    },
    {
      id: 23,
      type: 'status_changed',
      issueId: 103,
      issueTitle: 'Implement dark mode',
      userId: 1,
      user: users[0],
      data: {
        fromStatus: 'backlog',
        toStatus: 'selected',
      },
      isRead: true,
      createdAt: daysAgo(6, 9, 5),
    },
    {
      id: 24,
      type: 'assignee_added',
      issueId: 103,
      issueTitle: 'Implement dark mode',
      userId: 1,
      user: users[0],
      data: {
        assigneeName: 'Lord Gaben',
      },
      isRead: true,
      createdAt: daysAgo(6, 10, 30),
    },
    {
      id: 25,
      type: 'issue_created',
      issueId: 102,
      issueTitle: 'Fix login form validation',
      userId: 2,
      user: users[1],
      data: {},
      isRead: true,
      createdAt: daysAgo(6, 15, 0),
    },
    {
      id: 26,
      type: 'assignee_added',
      issueId: 102,
      issueTitle: 'Fix login form validation',
      userId: 2,
      user: users[1],
      data: {
        assigneeName: 'Pickle Rick',
      },
      isRead: true,
      createdAt: daysAgo(6, 15, 10),
    },
    {
      id: 27,
      type: 'issue_created',
      issueId: 101,
      issueTitle: 'Add new navigation component',
      userId: 1,
      user: users[0],
      data: {},
      isRead: true,
      createdAt: daysAgo(7, 1, 0),
    },
    {
      id: 28,
      type: 'estimate_changed',
      issueId: 104,
      issueTitle: 'Update API documentation',
      userId: 3,
      user: users[2],
      data: {
        oldEstimate: 8,
        newEstimate: 6,
      },
      isRead: true,
      createdAt: daysAgo(7, 5, 30),
    },
  ],
};

export const getActivityById = activityId => {
  const activity = activitiesData.activities.find(a => a.id === parseInt(activityId, 10));
  return activity;
};
