export const issuesData = {
  issues: [
    {
      id: 101,
      title: 'Add new navigation component',
      type: 'task',
      status: 'backlog',
      priority: '3',
      listPosition: 1,
      description: 'Create a responsive navigation component with mobile support',
      descriptionText: 'Create a responsive navigation component with mobile support',
      estimate: 8,
      timeSpent: 0,
      timeRemaining: 8,
      reporterId: 1,
      projectId: 1,
      userIds: [1, 2],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
      ],
      comments: [],
      startDate: '2020-06-01T00:00:00.000Z',
      dueDate: '2020-06-10T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
    {
      id: 102,
      title: 'Fix login form validation',
      type: 'bug',
      status: 'selected',
      priority: '2',
      listPosition: 1,
      description: 'Login form does not validate email format correctly',
      descriptionText: 'Login form does not validate email format correctly',
      estimate: 4,
      timeSpent: 2,
      timeRemaining: 2,
      reporterId: 2,
      projectId: 1,
      userIds: [2],
      users: [
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
      ],
      comments: [],
      startDate: '2020-06-02T00:00:00.000Z',
      dueDate: '2020-06-05T00:00:00.000Z',
      dependencies: [101],
      createdAt: '2020-06-02T00:00:00.000Z',
      updatedAt: '2020-06-02T00:00:00.000Z',
    },
    {
      id: 103,
      title: 'Implement dark mode',
      type: 'story',
      status: 'inprogress',
      priority: '3',
      listPosition: 1,
      description: 'Add dark mode theme support across the application',
      descriptionText: 'Add dark mode theme support across the application',
      estimate: 16,
      timeSpent: 8,
      timeRemaining: 8,
      reporterId: 1,
      projectId: 1,
      userIds: [1, 3],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      comments: [
        {
          id: 201,
          body: 'Great progress so far! The theme switcher looks good.',
          issueId: 103,
          userId: 2,
          user: {
            id: 2,
            name: 'Pickle Rick',
            avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
          },
          createdAt: '2020-06-05T00:00:00.000Z',
          updatedAt: '2020-06-05T00:00:00.000Z',
        },
      ],
      startDate: '2020-06-03T00:00:00.000Z',
      dueDate: '2020-06-20T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-03T00:00:00.000Z',
      updatedAt: '2020-06-03T00:00:00.000Z',
    },
    {
      id: 104,
      title: 'Update API documentation',
      type: 'task',
      status: 'done',
      priority: '4',
      listPosition: 1,
      description: 'Update all API endpoints documentation with examples',
      descriptionText: 'Update all API endpoints documentation with examples',
      estimate: 6,
      timeSpent: 6,
      timeRemaining: 0,
      reporterId: 3,
      projectId: 1,
      userIds: [3],
      users: [
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      comments: [],
      startDate: '2020-06-04T00:00:00.000Z',
      dueDate: '2020-06-06T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-04T00:00:00.000Z',
      updatedAt: '2020-06-04T00:00:00.000Z',
    },
  ],
};

// Individual issue details (for /issues/:id endpoint)
export const getIssueById = (id) => {
  const issue = issuesData.issues.find(item => item.id === parseInt(id));
  return issue || issuesData.issues[0]; // Fallback to first issue if not found
};
