export const projectData = {
  id: 1,
  name: 'Singularity 1.0',
  url: 'https://www.atlassian.com/software/jira',
  description:
    'Plan, track, and manage your agile and software development projects in Jira. Customize your workflow, collaborate, and release great software.',
  category: 'software',
  createdAt: '2020-06-01T00:00:00.000Z',
  updatedAt: '2020-06-01T00:00:00.000Z',
  workflow: {
    columns: [
      { id: 'backlog', title: 'Backlog', color: '#dfe1e6', wipLimit: 0, position: 0 },
      { id: 'selected', title: 'Selected for Dev', color: '#dfe1e6', wipLimit: 5, position: 1 },
      { id: 'inprogress', title: 'In Progress', color: '#0052cc', wipLimit: 3, position: 2 },
      { id: 'review', title: 'In Review', color: '#FF991F', wipLimit: 2, position: 3 },
      { id: 'done', title: 'Done', color: '#0B875B', wipLimit: 0, position: 4 },
    ],
    transitions: {
      backlog: ['selected'],
      selected: ['backlog', 'inprogress'],
      inprogress: ['selected', 'review'],
      review: ['inprogress', 'done'],
      done: ['review'],
    },
  },
  users: [
    {
      id: 1,
      name: 'Lord Gaben',
      avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
      email: 'gaben@jira.guest',
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
    {
      id: 2,
      name: 'Pickle Rick',
      avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
      email: 'pickle.rick@jira.guest',
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
    {
      id: 3,
      name: 'Baby Yoda',
      avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
      email: 'baby.yoda@jira.guest',
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
  ],
  issues: [
    {
      id: 101,
      title: 'Add new navigation component',
      type: 'task',
      status: 'backlog',
      priority: '3',
      listPosition: 1,
      description: 'Create a responsive navigation component with mobile support',
      descriptionText: 'Create a responsive navigation component with mobile support',
      estimate: 8,
      timeSpent: 0,
      timeRemaining: 8,
      reporterId: 1,
      projectId: 1,
      userIds: [1, 2],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
      ],
      productArea: 'Frontend',
      startDate: '2020-06-01T00:00:00.000Z',
      dueDate: '2020-06-10T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
    {
      id: 102,
      title: 'Fix login form validation',
      type: 'bug',
      status: 'backlog',
      priority: '2',
      listPosition: 2,
      description: 'Login form does not validate email format correctly',
      descriptionText: 'Login form does not validate email format correctly',
      estimate: 4,
      timeSpent: 2,
      timeRemaining: 2,
      reporterId: 2,
      projectId: 1,
      userIds: [2],
      users: [
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
      ],
      productArea: 'Authentication',
      startDate: '2020-06-02T00:00:00.000Z',
      dueDate: '2020-06-05T00:00:00.000Z',
      dependencies: [101],
      createdAt: '2020-06-02T00:00:00.000Z',
      updatedAt: '2020-06-02T00:00:00.000Z',
    },
    {
      id: 103,
      title: 'Refactor authentication flow',
      type: 'task',
      status: 'backlog',
      priority: '4',
      listPosition: 3,
      description: 'Improve security and performance of authentication',
      descriptionText: 'Improve security and performance of authentication',
      estimate: 12,
      timeSpent: 0,
      timeRemaining: 12,
      reporterId: 2,
      projectId: 1,
      userIds: [2],
      users: [
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
      ],
      productArea: 'Backend',
      startDate: '2020-06-01T00:00:00.000Z',
      dueDate: '2020-06-15T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
    {
      id: 104,
      title: 'Design new dashboard layout',
      type: 'story',
      status: 'selected',
      priority: '3',
      listPosition: 1,
      description: 'Add dark mode theme support across the application',
      descriptionText: 'Add dark mode theme support across the application',
      estimate: 16,
      timeSpent: 8,
      timeRemaining: 8,
      reporterId: 1,
      projectId: 1,
      userIds: [1, 3],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'UI/UX',
      startDate: '2020-06-03T00:00:00.000Z',
      dueDate: '2020-06-20T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-03T00:00:00.000Z',
      updatedAt: '2020-06-03T00:00:00.000Z',
    },
    {
      id: 105,
      title: 'Optimize database queries',
      type: 'task',
      status: 'selected',
      priority: '5',
      listPosition: 2,
      description: 'Improve performance of slow queries',
      descriptionText: 'Improve performance of slow queries',
      estimate: 8,
      timeSpent: 0,
      timeRemaining: 8,
      reporterId: 1,
      projectId: 1,
      userIds: [1],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
      ],
      productArea: 'Backend',
      startDate: '2020-06-05T00:00:00.000Z',
      dueDate: '2020-06-12T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-05T00:00:00.000Z',
      updatedAt: '2020-06-05T00:00:00.000Z',
    },
    {
      id: 106,
      title: 'Implement dark mode',
      type: 'story',
      status: 'inprogress',
      priority: '3',
      listPosition: 1,
      description: 'Add dark mode theme support across the application',
      descriptionText: 'Add dark mode theme support across the application',
      estimate: 16,
      timeSpent: 8,
      timeRemaining: 8,
      reporterId: 1,
      projectId: 1,
      userIds: [1, 3],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'UI/UX',
      startDate: '2020-06-03T00:00:00.000Z',
      dueDate: '2020-06-20T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-03T00:00:00.000Z',
      updatedAt: '2020-06-03T00:00:00.000Z',
    },
    {
      id: 107,
      title: 'Add email notifications',
      type: 'task',
      status: 'inprogress',
      priority: '4',
      listPosition: 2,
      description: 'Send email notifications for important events',
      descriptionText: 'Send email notifications for important events',
      estimate: 10,
      timeSpent: 4,
      timeRemaining: 6,
      reporterId: 2,
      projectId: 1,
      userIds: [2, 3],
      users: [
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'Backend',
      startDate: '2020-06-06T00:00:00.000Z',
      dueDate: '2020-06-15T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-06T00:00:00.000Z',
      updatedAt: '2020-06-06T00:00:00.000Z',
    },
    {
      id: 108,
      title: 'Fix critical security vulnerability',
      type: 'bug',
      status: 'inprogress',
      priority: '5',
      listPosition: 3,
      description: 'Address XSS vulnerability in comment system',
      descriptionText: 'Address XSS vulnerability in comment system',
      estimate: 6,
      timeSpent: 3,
      timeRemaining: 3,
      reporterId: 1,
      projectId: 1,
      userIds: [1],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
      ],
      productArea: 'Security',
      startDate: '2020-06-07T00:00:00.000Z',
      dueDate: '2020-06-09T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-07T00:00:00.000Z',
      updatedAt: '2020-06-07T00:00:00.000Z',
    },
    {
      id: 109,
      title: 'Code review for authentication changes',
      type: 'task',
      status: 'review',
      priority: '4',
      listPosition: 1,
      description: 'Review authentication flow refactoring',
      descriptionText: 'Review authentication flow refactoring',
      estimate: 4,
      timeSpent: 3,
      timeRemaining: 1,
      reporterId: 3,
      projectId: 1,
      userIds: [3],
      users: [
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'Backend',
      startDate: '2020-06-08T00:00:00.000Z',
      dueDate: '2020-06-10T00:00:00.000Z',
      dependencies: [103],
      createdAt: '2020-06-08T00:00:00.000Z',
      updatedAt: '2020-06-08T00:00:00.000Z',
    },
    {
      id: 110,
      title: 'Test new API endpoints',
      type: 'task',
      status: 'review',
      priority: '3',
      listPosition: 2,
      description: 'Write integration tests for new API endpoints',
      descriptionText: 'Write integration tests for new API endpoints',
      estimate: 8,
      timeSpent: 7,
      timeRemaining: 1,
      reporterId: 2,
      projectId: 1,
      userIds: [2, 1],
      users: [
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
      ],
      productArea: 'Testing',
      startDate: '2020-06-09T00:00:00.000Z',
      dueDate: '2020-06-11T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-09T00:00:00.000Z',
      updatedAt: '2020-06-09T00:00:00.000Z',
    },
    {
      id: 111,
      title: 'Update user documentation',
      type: 'task',
      status: 'done',
      priority: '2',
      listPosition: 1,
      description: 'Update user guide with new features',
      descriptionText: 'Update user guide with new features',
      estimate: 6,
      timeSpent: 6,
      timeRemaining: 0,
      reporterId: 3,
      projectId: 1,
      userIds: [3],
      users: [
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'Documentation',
      startDate: '2020-06-04T00:00:00.000Z',
      dueDate: '2020-06-06T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-04T00:00:00.000Z',
      updatedAt: '2020-06-10T00:00:00.000Z',
    },
    {
      id: 112,
      title: 'Setup CI/CD pipeline',
      type: 'task',
      status: 'done',
      priority: '4',
      listPosition: 2,
      description: 'Configure automated build and deployment',
      descriptionText: 'Configure automated build and deployment',
      estimate: 12,
      timeSpent: 12,
      timeRemaining: 0,
      reporterId: 1,
      projectId: 1,
      userIds: [1, 2],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
      ],
      productArea: 'DevOps',
      startDate: '2020-05-28T00:00:00.000Z',
      dueDate: '2020-06-03T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-05-28T00:00:00.000Z',
      updatedAt: '2020-06-03T00:00:00.000Z',
    },
    {
      id: 113,
      title: 'Migrate to new database version',
      type: 'task',
      status: 'backlog',
      priority: '3',
      listPosition: 4,
      description: 'Upgrade database to latest stable version',
      descriptionText: 'Upgrade database to latest stable version',
      estimate: 16,
      timeSpent: 0,
      timeRemaining: 16,
      reporterId: 1,
      projectId: 1,
      userIds: [1],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
      ],
      productArea: 'Backend',
      startDate: '2020-06-15T00:00:00.000Z',
      dueDate: '2020-06-30T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
    {
      id: 114,
      title: 'Add file upload feature',
      type: 'story',
      status: 'selected',
      priority: '3',
      listPosition: 3,
      description: 'Allow users to upload and attach files to issues',
      descriptionText: 'Allow users to upload and attach files to issues',
      estimate: 20,
      timeSpent: 0,
      timeRemaining: 20,
      reporterId: 2,
      projectId: 1,
      userIds: [2, 3],
      users: [
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'Frontend',
      startDate: '2020-06-10T00:00:00.000Z',
      dueDate: '2020-06-25T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-10T00:00:00.000Z',
      updatedAt: '2020-06-10T00:00:00.000Z',
    },
    {
      id: 115,
      title: 'Implement user permissions system',
      type: 'story',
      status: 'backlog',
      priority: '5',
      listPosition: 5,
      description: 'Add role-based access control',
      descriptionText: 'Add role-based access control',
      estimate: 24,
      timeSpent: 0,
      timeRemaining: 24,
      reporterId: 3,
      projectId: 1,
      userIds: [1, 2, 3],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'Backend',
      startDate: '2020-06-20T00:00:00.000Z',
      dueDate: '2020-07-10T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
  ],
};

export default projectData;
