export const projectData = {
  id: 1,
  name: 'Singularity 1.0',
  url: 'https://www.atlassian.com/software/jira',
  description:
    'Plan, track, and manage your agile and software development projects in Jira. Customize your workflow, collaborate, and release great software.',
  category: 'software',
  createdAt: '2020-06-01T00:00:00.000Z',
  updatedAt: '2020-06-01T00:00:00.000Z',
  users: [
    {
      id: 1,
      name: 'Lord Gaben',
      avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
      email: 'gaben@jira.guest',
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
    {
      id: 2,
      name: 'Pickle Rick',
      avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
      email: 'pickle.rick@jira.guest',
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
    {
      id: 3,
      name: 'Baby Yoda',
      avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
      email: 'baby.yoda@jira.guest',
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
  ],
  issues: [
    {
      id: 101,
      title: 'Add new navigation component',
      type: 'task',
      status: 'backlog',
      priority: '3',
      listPosition: 1,
      description: 'Create a responsive navigation component with mobile support',
      descriptionText: 'Create a responsive navigation component with mobile support',
      estimate: 8,
      timeSpent: 0,
      timeRemaining: 8,
      reporterId: 1,
      projectId: 1,
      userIds: [1, 2],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
      ],
      productArea: 'Frontend',
      startDate: '2020-06-01T00:00:00.000Z',
      dueDate: '2020-06-10T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-01T00:00:00.000Z',
    },
    {
      id: 102,
      title: 'Fix login form validation',
      type: 'bug',
      status: 'selected',
      priority: '2',
      listPosition: 1,
      description: 'Login form does not validate email format correctly',
      descriptionText: 'Login form does not validate email format correctly',
      estimate: 4,
      timeSpent: 2,
      timeRemaining: 2,
      reporterId: 2,
      projectId: 1,
      userIds: [2],
      users: [
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
      ],
      productArea: 'Authentication',
      startDate: '2020-06-02T00:00:00.000Z',
      dueDate: '2020-06-05T00:00:00.000Z',
      dependencies: [101],
      createdAt: '2020-06-02T00:00:00.000Z',
      updatedAt: '2020-06-02T00:00:00.000Z',
    },
    {
      id: 103,
      title: 'Implement dark mode',
      type: 'story',
      status: 'inprogress',
      priority: '3',
      listPosition: 1,
      description: 'Add dark mode theme support across the application',
      descriptionText: 'Add dark mode theme support across the application',
      estimate: 16,
      timeSpent: 8,
      timeRemaining: 8,
      reporterId: 1,
      projectId: 1,
      userIds: [1, 3],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'UI/UX',
      startDate: '2020-06-03T00:00:00.000Z',
      dueDate: '2020-06-20T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-03T00:00:00.000Z',
      updatedAt: '2020-06-03T00:00:00.000Z',
    },
    {
      id: 104,
      title: 'Update API documentation',
      type: 'task',
      status: 'done',
      priority: '4',
      listPosition: 1,
      description: 'Update all API endpoints documentation with examples',
      descriptionText: 'Update all API endpoints documentation with examples',
      estimate: 6,
      timeSpent: 6,
      timeRemaining: 0,
      reporterId: 3,
      projectId: 1,
      userIds: [3],
      users: [
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'Backend',
      startDate: '2020-06-04T00:00:00.000Z',
      dueDate: '2020-06-06T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-04T00:00:00.000Z',
      updatedAt: '2020-06-04T00:00:00.000Z',
    },
    {
      id: 105,
      title: 'Refactor authentication service',
      type: 'task',
      status: 'inprogress',
      priority: '2',
      listPosition: 2,
      description: 'Refactor the authentication service to use JWT tokens',
      descriptionText: 'Refactor the authentication service to use JWT tokens',
      estimate: 12,
      timeSpent: 5,
      timeRemaining: 7,
      reporterId: 1,
      projectId: 1,
      userIds: [1],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
      ],
      productArea: 'Backend',
      startDate: '2020-06-05T00:00:00.000Z',
      dueDate: '2020-06-12T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-05T00:00:00.000Z',
      updatedAt: '2020-06-07T00:00:00.000Z',
    },
    {
      id: 106,
      title: 'Design new landing page',
      type: 'story',
      status: 'backlog',
      priority: '3',
      listPosition: 2,
      description: 'Create designs for the new landing page with hero section',
      descriptionText: 'Create designs for the new landing page with hero section',
      estimate: 10,
      timeSpent: 0,
      timeRemaining: 10,
      reporterId: 2,
      projectId: 1,
      userIds: [2, 3],
      users: [
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'Design',
      startDate: '2020-06-08T00:00:00.000Z',
      dueDate: '2020-06-18T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-05T00:00:00.000Z',
      updatedAt: '2020-06-06T00:00:00.000Z',
    },
    {
      id: 107,
      title: 'Critical security vulnerability in auth',
      type: 'bug',
      status: 'inprogress',
      priority: '5',
      listPosition: 3,
      description: 'Fix critical security vulnerability allowing token bypass',
      descriptionText: 'Fix critical security vulnerability allowing token bypass',
      estimate: 8,
      timeSpent: 6,
      timeRemaining: 2,
      reporterId: 3,
      projectId: 1,
      userIds: [1, 2],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
      ],
      productArea: 'Security',
      startDate: '2020-06-06T00:00:00.000Z',
      dueDate: '2020-06-07T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-06T00:00:00.000Z',
      updatedAt: '2020-06-08T12:30:00.000Z',
    },
    {
      id: 108,
      title: 'Add search functionality',
      type: 'story',
      status: 'selected',
      priority: '3',
      listPosition: 2,
      description: 'Implement global search with filters and facets',
      descriptionText: 'Implement global search with filters and facets',
      estimate: 20,
      timeSpent: 0,
      timeRemaining: 20,
      reporterId: 1,
      projectId: 1,
      userIds: [3],
      users: [
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'Frontend',
      startDate: '2020-06-07T00:00:00.000Z',
      dueDate: '2020-06-25T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-06T00:00:00.000Z',
      updatedAt: '2020-06-07T00:00:00.000Z',
    },
    {
      id: 109,
      title: 'Fix mobile navigation overflow',
      type: 'bug',
      status: 'done',
      priority: '3',
      listPosition: 2,
      description: 'Navigation menu overflows on mobile devices',
      descriptionText: 'Navigation menu overflows on mobile devices',
      estimate: 3,
      timeSpent: 3,
      timeRemaining: 0,
      reporterId: 2,
      projectId: 1,
      userIds: [2],
      users: [
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
      ],
      productArea: 'Frontend',
      startDate: '2020-06-03T00:00:00.000Z',
      dueDate: '2020-06-04T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-03T00:00:00.000Z',
      updatedAt: '2020-06-05T00:00:00.000Z',
    },
    {
      id: 110,
      title: 'Setup CI/CD pipeline',
      type: 'task',
      status: 'done',
      priority: '4',
      listPosition: 3,
      description: 'Configure automated testing and deployment pipeline',
      descriptionText: 'Configure automated testing and deployment pipeline',
      estimate: 14,
      timeSpent: 14,
      timeRemaining: 0,
      reporterId: 1,
      projectId: 1,
      userIds: [1, 3],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'DevOps',
      startDate: '2020-06-01T00:00:00.000Z',
      dueDate: '2020-06-05T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-05T18:00:00.000Z',
    },
    {
      id: 111,
      title: 'Optimize database queries',
      type: 'task',
      status: 'backlog',
      priority: '2',
      listPosition: 3,
      description: 'Add indexes and optimize slow database queries',
      descriptionText: 'Add indexes and optimize slow database queries',
      estimate: null,
      timeSpent: 0,
      timeRemaining: null,
      reporterId: 3,
      projectId: 1,
      userIds: [1],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
      ],
      productArea: 'Backend',
      startDate: null,
      dueDate: null,
      dependencies: [],
      createdAt: '2020-06-07T00:00:00.000Z',
      updatedAt: '2020-06-07T10:00:00.000Z',
    },
    {
      id: 112,
      title: 'Implement user notifications',
      type: 'story',
      status: 'selected',
      priority: '4',
      listPosition: 3,
      description: 'Add real-time notifications for user actions and updates',
      descriptionText: 'Add real-time notifications for user actions and updates',
      estimate: null,
      timeSpent: 0,
      timeRemaining: null,
      reporterId: 2,
      projectId: 1,
      userIds: [2, 3],
      users: [
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'Frontend',
      startDate: '2020-06-10T00:00:00.000Z',
      dueDate: '2020-06-20T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-07T00:00:00.000Z',
      updatedAt: '2020-06-08T09:15:00.000Z',
    },
    {
      id: 113,
      title: 'Memory leak in dashboard',
      type: 'bug',
      status: 'backlog',
      priority: '1',
      listPosition: 4,
      description: 'Dashboard component causes memory leak after 30 minutes',
      descriptionText: 'Dashboard component causes memory leak after 30 minutes',
      estimate: 5,
      timeSpent: 0,
      timeRemaining: 5,
      reporterId: 1,
      projectId: 1,
      userIds: [],
      users: [],
      productArea: 'Frontend',
      startDate: null,
      dueDate: null,
      dependencies: [],
      createdAt: '2020-06-08T00:00:00.000Z',
      updatedAt: '2020-06-08T14:20:00.000Z',
    },
    {
      id: 114,
      title: 'Add export to CSV feature',
      type: 'task',
      status: 'done',
      priority: '3',
      listPosition: 4,
      description: 'Allow users to export reports and data to CSV format',
      descriptionText: 'Allow users to export reports and data to CSV format',
      estimate: 7,
      timeSpent: 8,
      timeRemaining: 0,
      reporterId: 2,
      projectId: 1,
      userIds: [3],
      users: [
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'Reports',
      startDate: '2020-06-02T00:00:00.000Z',
      dueDate: '2020-06-04T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-02T00:00:00.000Z',
      updatedAt: '2020-06-05T16:45:00.000Z',
    },
    {
      id: 115,
      title: 'Create onboarding tutorial',
      type: 'story',
      status: 'done',
      priority: '4',
      listPosition: 5,
      description: 'Design and implement interactive onboarding flow for new users',
      descriptionText: 'Design and implement interactive onboarding flow for new users',
      estimate: 18,
      timeSpent: 20,
      timeRemaining: 0,
      reporterId: 3,
      projectId: 1,
      userIds: [1, 2, 3],
      users: [
        {
          id: 1,
          name: 'Lord Gaben',
          avatarUrl: 'https://i.ibb.co/6n0hLML/lord-gaben.jpg',
        },
        {
          id: 2,
          name: 'Pickle Rick',
          avatarUrl: 'https://i.ibb.co/7JM1P0V/pickle-rick.png',
        },
        {
          id: 3,
          name: 'Baby Yoda',
          avatarUrl: 'https://i.ibb.co/6PrN4M5/baby-yoda.jpg',
        },
      ],
      productArea: 'UI/UX',
      startDate: '2020-06-01T00:00:00.000Z',
      dueDate: '2020-06-08T00:00:00.000Z',
      dependencies: [],
      createdAt: '2020-06-01T00:00:00.000Z',
      updatedAt: '2020-06-08T17:30:00.000Z',
    },
  ],
};

export default projectData;
